### ISSUE TITLE
'More' URL is parsed incorrectly

### ISSUE THREAD

**Issue by tschoffelen** [RusticiSoftware/TinCanStatementViewer#16]
The /statements endpoint returns "more" with a value of:

    http://localhost:3000/xAPI/statements?limit=25&related_activities=false&related_agents...

And the StatementViewer tries to load the following:

    http://localhost:3000/http://localhost:3000/xAPI/statements?limit=25&related_activities...

**Comment by garemoko** [comment]
@tschoffelen 

This sounds like an LRS bug. Which LRS are you using? The more property is supposed to be a "Relative IRL...including the full path and optionally a query string but excluding scheme, host, and port."

See https://github.com/adlnet/xAPI-Spec/blob/master/xAPI.md#42-retrieval-of-statements

It might also be worth you looking at the [conformance test suite](http://tincanapi.com/conformance-test/), which I believe would pick up the LRS error here: https://github.com/adlnet/xAPI_LRS_Test/blob/1d684b7798f05a2f11f916c441c43dd4ba65486c/src/tasks/reset.js#L52-L67

**Comment by tschoffelen** [comment]
Apologies, my mistake. I was using the test suite below, which is apparently incorrect on that point:
https://github.com/adlnet/lrs-conformance-test-suite

**Comment by garemoko** [comment]
Thanks for the further info @tschoffelen - one more question: does the test suite you used specifically require the more property to be an absolute URL, or is it just that it doesn't test that?

**Comment by tschoffelen** [comment]
It fails on anything other than an absolute URL. Thanks for pointing our that the spec requires a relative IRL.

**Comment by garemoko** [comment]
Thanks, that's helpful. I'll log this as an issue on that test.
